name: 'Verify KubeBuilder PRs'
description: 'Verify PRs for the KubeBuilder project repos & similar'
inputs:
  github_token:
    description: "the github_token provided by the actions runner"
    required: true
runs:
  using: docker
  # this is built using GCB by building the Dockerfile in this directory on
  # every tagged release.  After tagging a release, a new version should
  # automatically appear.
  image: 'docker://gcr.io/kubebuilder/pr-verifier:v0.4.1'
